<package format="3">
  <name>swarmcomm_msgs</name>
  <version>0.0.1</version>
  <description>ROS2 version of swarmcomm_msgs</description>

  <maintainer email="xuhao3e8@gmail.com">xuhao3e8</maintainer>
  <license>Apache-2.0</license>
  
  <!-- buildtool_depend: 用于构建的依赖 -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- 编译和运行时需要的依赖 -->
  <build_depend>geometry_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>

  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <!-- 指明这是一个 ROS2 interface package -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
