"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import LandmarkDescriptor_t

class LandmarkDescriptorPacket_t(object):
    __slots__ = ["drone_id", "landmark_num", "landmarks"]

    __typenames__ = ["int32_t", "int32_t", "LandmarkDescriptor_t"]

    __dimensions__ = [None, None, ["landmark_num"]]

    def __init__(self):
        self.drone_id = 0
        self.landmark_num = 0
        self.landmarks = []

    def encode(self):
        buf = BytesIO()
        buf.write(LandmarkDescriptorPacket_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.drone_id, self.landmark_num))
        for i0 in range(self.landmark_num):
            assert self.landmarks[i0]._get_packed_fingerprint() == LandmarkDescriptor_t._get_packed_fingerprint()
            self.landmarks[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != LandmarkDescriptorPacket_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return LandmarkDescriptorPacket_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = LandmarkDescriptorPacket_t()
        self.drone_id, self.landmark_num = struct.unpack(">ii", buf.read(8))
        self.landmarks = []
        for i0 in range(self.landmark_num):
            self.landmarks.append(LandmarkDescriptor_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if LandmarkDescriptorPacket_t in parents: return 0
        newparents = parents + [LandmarkDescriptorPacket_t]
        tmphash = (0xbd77462e2459b09c+ LandmarkDescriptor_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if LandmarkDescriptorPacket_t._packed_fingerprint is None:
            LandmarkDescriptorPacket_t._packed_fingerprint = struct.pack(">Q", LandmarkDescriptorPacket_t._get_hash_recursive([]))
        return LandmarkDescriptorPacket_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", LandmarkDescriptorPacket_t._get_packed_fingerprint())[0]

