"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import Time_t

class LoopInliers_t(object):
    __slots__ = ["ts", "sender_id", "drone_id_a", "drone_id_b", "inlier_id_size", "inlier_ids"]

    __typenames__ = ["Time_t", "int32_t", "int32_t", "int32_t", "int32_t", "int64_t"]

    __dimensions__ = [None, None, None, None, None, ["inlier_id_size"]]

    def __init__(self):
        self.ts = Time_t()
        self.sender_id = 0
        self.drone_id_a = 0
        self.drone_id_b = 0
        self.inlier_id_size = 0
        self.inlier_ids = []

    def encode(self):
        buf = BytesIO()
        buf.write(LoopInliers_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.ts._get_packed_fingerprint() == Time_t._get_packed_fingerprint()
        self.ts._encode_one(buf)
        buf.write(struct.pack(">iiii", self.sender_id, self.drone_id_a, self.drone_id_b, self.inlier_id_size))
        buf.write(struct.pack('>%dq' % self.inlier_id_size, *self.inlier_ids[:self.inlier_id_size]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != LoopInliers_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return LoopInliers_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = LoopInliers_t()
        self.ts = Time_t._decode_one(buf)
        self.sender_id, self.drone_id_a, self.drone_id_b, self.inlier_id_size = struct.unpack(">iiii", buf.read(16))
        self.inlier_ids = struct.unpack('>%dq' % self.inlier_id_size, buf.read(self.inlier_id_size * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if LoopInliers_t in parents: return 0
        newparents = parents + [LoopInliers_t]
        tmphash = (0x84881040f9cfc843+ Time_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if LoopInliers_t._packed_fingerprint is None:
            LoopInliers_t._packed_fingerprint = struct.pack(">Q", LoopInliers_t._get_hash_recursive([]))
        return LoopInliers_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

