"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import Time_t

class SlidingWindow_t(object):
    __slots__ = ["timestamp", "drone_id", "sld_win_len", "frame_ids"]

    __typenames__ = ["Time_t", "int32_t", "int32_t", "int64_t"]

    __dimensions__ = [None, None, None, ["sld_win_len"]]

    def __init__(self):
        self.timestamp = Time_t()
        self.drone_id = 0
        self.sld_win_len = 0
        self.frame_ids = []

    def encode(self):
        buf = BytesIO()
        buf.write(SlidingWindow_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.timestamp._get_packed_fingerprint() == Time_t._get_packed_fingerprint()
        self.timestamp._encode_one(buf)
        buf.write(struct.pack(">ii", self.drone_id, self.sld_win_len))
        buf.write(struct.pack('>%dq' % self.sld_win_len, *self.frame_ids[:self.sld_win_len]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != SlidingWindow_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return SlidingWindow_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = SlidingWindow_t()
        self.timestamp = Time_t._decode_one(buf)
        self.drone_id, self.sld_win_len = struct.unpack(">ii", buf.read(8))
        self.frame_ids = struct.unpack('>%dq' % self.sld_win_len, buf.read(self.sld_win_len * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if SlidingWindow_t in parents: return 0
        newparents = parents + [SlidingWindow_t]
        tmphash = (0xfbd6b3e36ce1914c+ Time_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if SlidingWindow_t._packed_fingerprint is None:
            SlidingWindow_t._packed_fingerprint = struct.pack(">Q", SlidingWindow_t._get_hash_recursive([]))
        return SlidingWindow_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

