"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Vector_t(object):
    __slots__ = ["size", "data"]

    __typenames__ = ["int32_t", "double"]

    __dimensions__ = [None, ["size"]]

    def __init__(self):
        self.size = 0
        self.data = []

    def encode(self):
        buf = BytesIO()
        buf.write(Vector_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.size))
        buf.write(struct.pack('>%dd' % self.size, *self.data[:self.size]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Vector_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Vector_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Vector_t()
        self.size = struct.unpack(">i", buf.read(4))[0]
        self.data = struct.unpack('>%dd' % self.size, buf.read(self.size * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Vector_t in parents: return 0
        tmphash = (0x4a29a0563145d11e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Vector_t._packed_fingerprint is None:
            Vector_t._packed_fingerprint = struct.pack(">Q", Vector_t._get_hash_recursive([]))
        return Vector_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

