/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __DroneState_t_hpp__
#define __DroneState_t_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>


class DroneState_t
{
    public:
        int32_t    drone_id;

        int32_t    id_num;

        std::vector< int8_t > grid_ids;

        double     recent_attempt_time;

        double     stamp;

        int32_t    len;

        std::vector< float > pos;

        std::vector< float > vel;

        float      yaw;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "DroneState_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int DroneState_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int DroneState_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int DroneState_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t DroneState_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* DroneState_t::getTypeName()
{
    return "DroneState_t";
}

int DroneState_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->drone_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->id_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->id_num > 0) {
        tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->grid_ids[0], this->id_num);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->recent_attempt_time, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->stamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->len, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->len > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->pos[0], this->len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->len > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->vel[0], this->len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->yaw, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int DroneState_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->drone_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->id_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->id_num) {
        this->grid_ids.resize(this->id_num);
        tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->grid_ids[0], this->id_num);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->recent_attempt_time, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->stamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->len, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->len) {
        this->pos.resize(this->len);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->pos[0], this->len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->len) {
        this->vel.resize(this->len);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->vel[0], this->len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->yaw, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int DroneState_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, this->id_num);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->len);
    enc_size += __float_encoded_array_size(NULL, this->len);
    enc_size += __float_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t DroneState_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x8e469c0bb34c4559LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
